Página de cadastro
ufersa/plataforma-sabia-app pull request #33
Opened 2021-02-07 03:59 UTC by davioliveiira

## Summary

Resolves #5

2021-02-07 03:59 UTC, davioliveiira commented
@mtullyoc pode pegar a partir desse PR e ajustar corretamente o cadastro, validações de form...

2021-02-07 22:29 UTC, lcnogueira requested changes
Muito bom! Deixei só uma sugestão relativa a estilos do Input que acho seria interessante fazermos.

2021-02-07 22:29 UTC, lcnogueira commented on src/screens/SignUp/index.tsx
> +            <S.InputWrapper>
Entendi que aqui adicionou o `TitleWrapper` pra adicionar uma margem entre cada Input. Porém, ao invés disso, acho que fica melhor simplesmente passarmos um `style`pro Input. Dessa forma, ele ficaria um pouco mais genérico, e poderíamos definir outros estilos quando necessário. Algo como
```js
<Input type="default" placeholder="Nome completo" style={{ marginBottom: 24 }} />
```
```js
interface InputProps extends TextInputProps {
  //outras propriedades aqui
  style?: {
    [property: string]: string | number
  }
}
```
```
<S.InputWrapper
      style={[{
        paddingVertical: multiline ? 12 : 0,
        height: multiline ? 122 : buildSize(size),
      }, style]}
```

2021-02-07 22:29 UTC, lcnogueira commented on src/screens/SignUp/index.tsx
> +              <S.Title>Informações Pessoais</S.Title>
Como esse título é um estilo específico do componente, podemos simplesmente definir a margin nele mesmo.

2021-02-07 22:29 UTC, lcnogueira commented on src/screens/SignUp/index.tsx
> +              <Input type="email-address" placeholder="E-mail" />
**Acho que tá fora do escopo desse PR, mas sim no PR da funcionalidade em si do login.**

@mtullyoc ,seria interessante definirmos uma "navegação" entre os inputs: quando o usuário estiver no 1 input e clicar no botão ("done" ou "next"), levaríamos ele pro próximo input. Atualmente, ele precisaria sempre ir tirando a mão do teclado e ir manualmente clicando no próximo input. 

Uma forma que pensei em fazer foi: usar um `useRef` pra controlar isso. Ex.: no e-mail, fazemos um `onSubmitEditing={() => passwordRef.current.focus()}`

E no input de senha, passamos:
```
const passwordRef = useRef()

<Input type="default" placeholder="Senha" ref={passwordRef}/>
```

E aí sucessivamente. Podemos também pensar num forma de fazer de modo mais genérico, usando um `useEffect` e `useRef` dentro do componente de Input...


'

2021-02-07 23:02 UTC, lcnogueira commented on src/screens/SignUp/index.tsx
> +              <Input type="email-address" placeholder="E-mail" />
Vou deixar aqui uma sugestão de implementação:
Dentro do `Input` component, teríamos algo como:
```js
  const [focused, setFocused] = useState(focus);
  const ref = useRef();

  useEffect(() => {
    if (ref.current && focus) {
      ref.current.focus();
    }
  }, [ref.current, focus]);

  function handleOnBlur(event) {
    setFocused(false);

    if (onBlur) {
      onBlur(event);
    }
  }
  ```
  E aí passaríamos pro `InputContainer`( é uma instância de TextInput):
  ```js
  <S.InputContainer
        ref={ref}
        onFocus={() => setFocused(true)}
        onBlur={handleOnBlur}
        onSubmitEditing={() => onSubmitEditing()}
```

E usaríamos o estado, pra alterar o estilo:
```js
style={[{
        paddingVertical: multiline ? 12 : 0,
        height: multiline ? 122 : buildSize(size),
      }, style, focused && { borderBottomColor: 'red' }]} //o border bottom foi só um exemplo. Usaríamos do figma
      
      
```

E dentro do SignUp, faríamos:
```js
const [focusedInput, setFocusedInput] = React.useState<string | null>(null);

<Input
    type="default"
    placeholder="Nome completo"
    onBlur={() => setFocusedInput(null)}
    onSubmitEditing={() => setFocusedInput('email')}
/>
<Input
    type="email-address"
    placeholder="E-mail"
    focus={focusedInput === 'email'}
    onSubmitEditing={() => setFocusedInput('senha')}
    onBlur={() => setFocusedInput(null)}
    />    
<Input 
   type="default" 
   name="senha" 
   placeholder="Senha" 
   focus={focusedInput === 'password'} 
   onBlur={() => setFocusedInput(null)} 
   onSubmitEditing={() => setFocusedInput('repeatPassword')} 
  />
<Input 
  type="default" 
  placeholder="Repetir senha" 
  focus={focusedInput === 'repeatPassword'} 
  onSubmitEditing={() => Keyboard.dismiss} 
  />
```

Essa aí seria a ideia geral...e aí ajustaríamos um detalhe ou outro...

2021-02-09 01:58 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +            <S.InputWrapper>
Done!

2021-02-09 01:59 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +              <S.Title>Informações Pessoais</S.Title>
Done!

2021-02-09 02:08 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +              <Input type="email-address" placeholder="E-mail" />
Criei a issue #35 para tratar disso.

2021-02-09 02:16 UTC, merged