Enhancements on inputs navigations and look n feel
ufersa/plataforma-sabia-app pull request #36
Opened 2021-02-10 10:00 UTC by mtullyoc

## Summary

Resolves #35 

![Input navigation](https://user-images.githubusercontent.com/17722915/107493877-e35b8d00-6b6c-11eb-9603-3806f24533a3.GIF)

@lcnogueira não consegui fazer de forma genérica, como você citou na Issue: `setFocusedInput('email')`. 

Se tiver uma luz aí, agradeço =)

2021-02-10 11:18 UTC, davioliveiira requested changes

2021-02-10 11:18 UTC, davioliveiira commented on src/screens/SignUp/index.tsx
> +            </S.ButtonWrapper>
Eu só removeria esse botão do `KeyboardAvoidingView` e deixaria ele sempre fixo no bottom da tela dentro da `SafeAreaView `

2021-02-10 22:04 UTC, lcnogueira commented on src/screens/SignUp/index.tsx
> +            </S.ButtonWrapper>
Boa. Fiz isso. Deixar dentro do keyboardavoidingview ficava jogando o botao de cima pra baixo ao sair de um input e "navegar" pro outro 👍

2021-02-11 01:37 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +            </S.ButtonWrapper>
Boa!

2021-02-11 01:39 UTC, merged