Funcionalidade de cadastro de usuário
ufersa/plataforma-sabia-app pull request #42
Opened 2021-02-11 18:17 UTC by mtullyoc

## Summary

Resolves #22

2021-02-16 13:42 UTC, davioliveiira requested changes

2021-02-16 13:42 UTC, davioliveiira commented on src/screens/SignUp/index.tsx
> +  repeatPassword: string;
@mtullyoc acho que podemos deixar o nomes dos campos mais intuitivos

2021-02-16 13:42 UTC, davioliveiira commented on src/screens/SignUp/index.tsx
> +      } else {
@mtullyoc talvez um validate no próprio input evite de fazer esse `if`

2021-02-16 22:36 UTC, lcnogueira commented on src/services/auth.ts
> +    full_name: fullname,
```suggestion
    full_name,
```

2021-02-18 01:37 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +      } else {
@davioliveiira vou melhorar isso ao fazer as validações dos forms. Fazer outra issue para isso.

2021-02-18 01:45 UTC, mtullyoc commented on src/screens/SignUp/index.tsx
> +  repeatPassword: string;
@davioliveiira done!

2021-02-18 01:46 UTC, mtullyoc commented on src/services/auth.ts
> +    full_name: fullname,
@lcnogueira done!

2021-02-18 11:57 UTC, davioliveiira approved these changes

2021-02-18 21:15 UTC, merged