[WIP] Feature search
ufersa/plataforma-sabia-app pull request #70
Opened 2021-03-04 21:44 UTC by davioliveiira

## Summary

Resolves #7

![simulator_screenshot_653704AC-043C-4678-81F7-D3816217A6EB](https://user-images.githubusercontent.com/5223683/110034821-a9b81500-7d19-11eb-8c7a-8888a327d109.png)

2021-03-05 05:08 UTC, mtullyoc reviewed
LGTM! 

|,,|_

2021-03-11 12:27 UTC, mateus4k commented on src/screens/Search/components/List/index.tsx
> +  // );
👀

2021-03-11 12:35 UTC, mateus4k commented on src/screens/Search/components/List/index.tsx
> +  // );
👀

2021-03-11 12:35 UTC, mateus4k commented on src/screens/Search/components/List/index.tsx
> +// import { View, Text, TouchableOpacity } from 'react-native';
```suggestion
```

2021-03-11 18:30 UTC, davioliveiira commented on src/screens/Search/components/List/index.tsx
> +  // );
Está em WIP ainda @mateus4k hehehe!

2021-03-11 18:30 UTC, davioliveiira commented on src/screens/Search/components/List/index.tsx
> +// import { View, Text, TouchableOpacity } from 'react-native';
Está em WIP ainda @mateus4k hehehe!

2021-03-11 20:06 UTC, mateus4k commented on src/screens/Search/components/List/index.tsx
> +// import { View, Text, TouchableOpacity } from 'react-native';
Foi mal kkkk

2021-03-17 03:36 UTC, mtullyoc requested changes
Good job! 
:)

2021-03-17 03:36 UTC, mtullyoc commented on src/screens/Search/index.tsx
> +  // useEffect(() => {}, [tab]);
```suggestion

```

2021-03-17 10:08 UTC, mtullyoc approved these changes

2021-03-17 13:48 UTC, mateus4k commented on src/screens/Search/index.tsx
> +  // useEffect(() => {}, [tab]);
```suggestion
```

2021-03-17 13:48 UTC, mateus4k commented on .env.example
> +ALGOLIA_INDEX_NAME_SERVICE=searchable_service_staging
```suggestion
ALGOLIA_INDEX_NAME_TECHNOLOGY=searchable_technology_staging
ALGOLIA_INDEX_NAME_SERVICE=searchable_service_staging
```
Anyway, it's better define this variables like `APP_ENV:staging` and `ALGOLIA_PREFIX:searchable` and generate the index name dynamically from "prefix + entity name (like `technology` or `service`) + ambient sufix 🤔

2021-03-18 16:52 UTC, merged