Página Inicial
ufersa/plataforma-sabia-app pull request #8
Opened 2021-01-07 22:45 UTC by davioliveiira

Resolves #1 
---
Página inicial do App com mocks e estado de loading nos cards

2021-01-20 00:06 UTC, lcnogueira requested changes

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Card/index.tsx
> +import styled from 'styled-components';
Na verdade, aqui devemos importar do pacote do native:
```
import styled from 'styled-components/native';
```

Dessa forma, tu vai ter acesso a usar o styled da maneira correta (inclusive com auto-complete):
```
const CardWrapper = styled.View`
```
<img width="708" alt="Screen Shot 2021-01-19 at 20 48 10" src="https://user-images.githubusercontent.com/12154623/105107808-a6353b00-5a97-11eb-982b-f636cf311fe1.png">

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Card/index.tsx
> +};
Talvez o teu plugin do eslint esteja desativado. Pelas regras aqui do meu eslint, ele nem deixa esse ponto-e-vírgula. Quando salva, ele já remove.

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Card/index.tsx
> +};
Talvez o teu plugin do eslint esteja desativado. Pelas regras aqui do meu eslint, ele nem deixa esse ponto-e-vírgula. Quando salva, ele já remove.

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Card/index.tsx
> +  backgroundColor: #ffffff;
Outro motivo que eu acho que tá desativado, é que, por exemplo, essa propriedade `backgroundColor` e `borderRadius` (em camelCase) nem existem. Aqui no styled-components seria `background-color` e `border-radius`.
<img width="574" alt="Screen Shot 2021-01-19 at 20 50 49" src="https://user-images.githubusercontent.com/12154623/105107977-04621e00-5a98-11eb-84e1-354cf5577d2f.png">

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Input/index.tsx
> +import styled from 'styled-components';
Mesma coisa que expliquei acima se aplica aqui nessa importação.

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Input/index.tsx
> +const InputWrapper = styled(View)`
```suggestion
const InputWrapper = styled.View`
```

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Input/index.tsx
> +const InputContainer = styled(TextInput)`
```suggestion
const InputContainer = styled.TextInput`
```

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Banks/BankCard.tsx
> +const Container = styled(View)`
```suggestion
const Container = styled.View`
```

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Banks/BankCard.tsx
> +const Title = styled(DefaultText)`
```suggestion
const Title = styled.DefaultText`
```

2021-01-20 00:06 UTC, lcnogueira commented on src/components/Input/index.tsx
> +
Vamos separar essa parte de estilos em um arquivo separado. Cada componente, fica com `Index.tsx` e um `styles.tsx`. Fica mais organizado.

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Banks/BankCard.tsx
> +  borderColor: #f5f5f5;
A gente precisa ver também uma forma de passar essas colors padrão aí pra os filhos. Atualmente, estamos usando as cores  em cada local. O melhor é padronizarmos em um arquivo e importamos ele aqui e usarmos. Assim, no dia que modificarmos, já teremos tudo alterado de uma vez. Além disso, faz com que a gente siga um padrão. Às vezes tem uma cor super parecida com a que já temos no arquivo de cores, então a gente substitui a do design e usa a do padrão, o que ajuda a manter um padrão de cores em toda a aplicação :bulb:.

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Banks/index.tsx
> +const BanksWrapper = styled(View)`
Seprar em um arquivo de styles

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Technologies/TechnologyCard.tsx
> +  const animatePulse = new Animated.Value(1);
Awesome!!! 💯

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Technologies/TechnologyCard.tsx
> +const CardWrapper = styled(View)`
Separar em um arquivo de estilos.

2021-01-20 00:06 UTC, lcnogueira commented on src/screens/Home/components/Technologies/TechnologyCard.tsx
> +    <FavoriteButton onPress={() => setState(!state)}>
```suggestion
    <FavoriteButton onPress={() => setState(previousState => !previousState)}>
```
Nesse caso, como o setState é assíncrono, pode acontecer um probleminha qnd o usuário clicar rapidamente: ele não fazer as atualizações em sequencia e acabar em um estado inconsistente. Ex.: tá não favoritado, o usuário clica 2 vezes. Ao invés de voltar para não favoritado, ficar como favoritado. Pra garantir que isso não aconteçã, temos de usar uma função (ela garante o retorno sempre do último estado alterado).

2021-01-20 12:24 UTC, davioliveiira commented on src/screens/Home/components/Banks/BankCard.tsx
> +  borderColor: #f5f5f5;
@lcnogueira boa ideia, vou abrir uma _issue_ pra isso: #15

2021-01-23 00:43 UTC, lcnogueira approved these changes

2021-01-24 15:02 UTC, merged